# Generated by Django 4.2.19 on 2025-02-23 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dialog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dialog",
                "verbose_name_plural": "Dialogs",
            },
        ),
        migrations.CreateModel(
            name="ItemST",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_steam_ID",
                    models.CharField(max_length=25, null=True, unique=True),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status_trade", models.BooleanField(default=True)),
                ("date_push_item", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserST",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=25)),
                ("registered_date", models.DateTimeField(auto_now_add=True)),
                ("trade_link", models.URLField(blank=True, default="")),
                ("count_buy", models.PositiveIntegerField(default=0)),
                ("count_sell", models.PositiveIntegerField(default=0)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
                ),
                ("inventory_json", models.JSONField(blank=True, default=dict)),
                ("steam_ID", models.CharField(max_length=17, unique=True)),
                ("email", models.EmailField(max_length=254, null=True, unique=True)),
                ("telegram", models.CharField(max_length=20, null=True, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Связанный пользователь Django.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userst",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Steam User",
                "verbose_name_plural": "Steam Users",
            },
        ),
        migrations.CreateModel(
            name="TradeST",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trade_status_st",
                    models.CharField(
                        choices=[
                            ("получен", "Получен"),
                            ("ожидает оплаты", "Ожидает оплаты"),
                            ("отменен", "Отменен"),
                        ],
                        default="ожидает оплаты",
                        max_length=15,
                    ),
                ),
                ("buyer_ID", models.CharField(max_length=17, null=True)),
                ("date_push_trade", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="web.itemst",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                ("msg_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "dialog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="web.dialog",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to="web.userst",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="web.userst",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="itemst",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="web.userst",
            ),
        ),
        migrations.AddField(
            model_name="dialog",
            name="last_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="web.message",
            ),
        ),
        migrations.AddField(
            model_name="dialog",
            name="participants",
            field=models.ManyToManyField(related_name="dialogs", to="web.userst"),
        ),
        migrations.AddIndex(
            model_name="userst",
            index=models.Index(
                fields=["steam_ID"], name="web_userst_steam_I_515df7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userst",
            index=models.Index(fields=["email"], name="web_userst_email_51d04a_idx"),
        ),
        migrations.AddIndex(
            model_name="userst",
            index=models.Index(
                fields=["telegram"], name="web_userst_telegra_4f78de_idx"
            ),
        ),
    ]
